import { NextResponse } from "next/server";
import { audioStore } from "@/lib/audio-store";

type RouteContext = { params: Promise<{ id: string }> };

/**
 * GET /api/audio/[id]
 * Serves an in-memory MP3 buffer generated by edge-tts for Twilio's <Play> verb.
 */
export async function GET(_req: Request, context: RouteContext) {
    const { id } = await context.params;
    const buffer = audioStore.get(id);

    if (!buffer) {
        return new NextResponse("Audio not found", { status: 404 });
    }

    return new NextResponse(new Uint8Array(buffer), {
        headers: {
            "Content-Type": "audio/mpeg",
            "Content-Length": buffer.length.toString(),
            "Cache-Control": "no-store",
        }
    });
}
